# Data exploration for the RPS database

In [1]:
# Kunal


import pandas as pd
import os

# Replace 'path_to_folder' with the actual path to your folder
folder_path = r'C://Users//SahilSingh//OneDrive - LongView//Documents//lng_exit//'

# Get a list of all files in the folder
files_in_folder = os.listdir(folder_path)

# Filter CSV files
csv_files = [file for file in files_in_folder if file.endswith('.csv')]

print(csv_files)

['rps_lng_addstore.csv', 'rps_lng_app.csv', 'rps_lng_appl.csv', 'rps_lng_app_a.csv', 'rps_lng_bnk.csv', 'rps_lng_cert.csv', 'rps_lng_cnt-cmp.csv', 'rps_lng_cnt.csv', 'rps_lng_cnt_a.csv', 'rps_lng_diary.csv', 'rps_lng_extra.csv', 'rps_lng_idcheck.csv', 'rps_lng_jnl.csv', 'rps_lng_jnlmisc.csv', 'rps_lng_keyjnl.csv', 'rps_lng_keyset.csv', 'rps_lng_lld.csv', 'rps_lng_lookup.csv', 'rps_lng_messages.csv', 'rps_lng_negs.csv', 'rps_lng_nomtran.csv', 'rps_lng_offers.csv', 'rps_lng_offers_a.csv', 'rps_lng_office.csv', 'rps_lng_pictures.csv', 'rps_lng_prp.csv', 'rps_lng_prplet.csv', 'rps_lng_prp_a.csv', 'rps_lng_src.csv', 'rps_lng_ten.csv', 'rps_lng_tenchk.csv', 'rps_lng_tenext.csv', 'rps_lng_workdet.csv', 'rps_lng_workhead.csv']

In [18]:
Lookup_csv = pd.read_csv(folder_path + csv_files[1])

In [20]:
Lookup_csv

,synchdel,synchrec,code,country,minprice,maxprice,retain,position,minrent,maxrent,...,type,offcode,negcode,srccode,notes,shared,active,register,amend,extra
0,0,2022-01-12 10:49:56,CHA190002,NaN,0,9999999,0,NaN,0.0,9999999.0,...,L,DRE,EDU,NaN,NaN,NaN,1,2019-02-25 16:32:54,2022-01-12 10:49:56,aToMatch='N'\r
1,0,2022-01-12 10:49:56,CHA190006,NaN,0,9999999,0,NaN,0.0,9999999.0,...,L,DRE,EDU,NaN,NaN,NaN,1,2019-03-07 14:12:58,2022-01-12 10:49:56,aToMatch='N'\raRentPeriod='M'
2,0,2019-08-19 11:35:54,CHA190009,NaN,0,9999999,0,NaN,0.0,9999999.0,...,L,CHA,OFJ,NaN,NaN,NaN,1,2019-03-14 11:04:47,2019-08-19 11:35:54,aToMatch='N'\r
3,0,2019-08-19 11:35:54,CHA190012,NaN,0,9999999,0,NaN,0.0,9999999.0,...,L,CHA,OFJ,NaN,NaN,NaN,1,2019-03-20 10:46:57,2019-08-19 11:35:54,aToMatch='N'\r
4,0,2019-08-19 11:35:54,CHA190026,NaN,0,9999999,0,NaN,0.0,9999999.0,...,L,CHA,OFJ,NaN,NaN,NaN,1,2019-04-24 11:28:06,2019-08-19 11:35:54,aToMatch='N'\r
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,0,2022-07-12 14:01:37,WES200034,NaN,0,9999999,0,NaN,0.0,9999999.0,...,L,WES,BDV,NaN,NaN,NaN,1,2020-03-31 13:47:49,2022-07-12 14:01:37,aToMatch='N'\r
1454,0,2022-07-12 14:01:37,WES200037,NaN,0,9999999,0,NaN,0.0,9999999.0,...,L,WES,BDV,NaN,NaN,NaN,1,2020-04-16 17:19:40,2022-07-12 14:01:37,aToMatch='N'\r
1455,0,2023-03-14 14:24:02,WES200044,NaN,0,9999999,0,NaN,0.0,9999999.0,...,L,WES,HKU,NaN,NaN,NaN,1,2020-05-04 13:10:24,2023-03-14 14:24:02,aToMatch='N'\r
1456,0,2022-08-09 09:08:05,WES200046,NaN,0,9999999,0,NaN,0.0,9999999.0,...,L,WES,NDK,NaN,NaN,NaN,1,2020-05-07 11:39:07,2022-08-09 09:08:05,aToMatch='N'\r
1457,0,2020-05-18 14:01:42,WES200051,NaN,0,9999999,0,NaN,0.0,9999999.0,...,L,WES,MEJ,NaN,NaN,NaN,1,2020-05-18 14:01:42,\N,aToMatch='N'\r

In [19]:
Lookup_csv['typeto'].unique()

KeyError: 'typeto'

In [8]:
Lookup_csv[Lookup_csv['typefrom'] == 'prp']

,synchdel,synchrec,code,typefrom,typeto,codefrom,codeto,register,amend
71,1,2020-02-25 10:05:02,CHA19000072,prp,cnt,HDO170233,CHA19000042,2019-04-09 10:32:05,2020-02-25 10:05:02
182,0,2019-07-17 12:26:40,CHA19000183,prp,cnt,HDO150132,HDO15000770,2019-07-17 12:26:40,\N
6891,0,2019-09-06 16:49:28,DRE19000217,prp,cnt,HDO100042,DRE19000115,2019-09-06 16:49:28,\N
6892,0,2019-09-06 17:25:16,DRE19000218,prp,cnt,HDO120581,DRE19000116,2019-09-06 17:25:16,\N
8650,1,2019-02-22 09:30:25,HDO07006555,prp,cnt,HDO070418,HDO17002537,2007-09-24 14:18:32,2019-02-22 09:30:25
...,...,...,...,...,...,...,...,...,...
105261,0,2019-07-01 13:20:45,RPT19041762,prp,ell,HDO150096,RPT150143,2019-07-01 13:20:45,\N
105262,0,2019-07-01 13:21:06,RPT19041763,prp,ell,HDO150108,RPT150143,2019-07-01 13:21:06,\N
105326,0,2021-02-16 13:38:21,RPT21000058,prp,ell,CVA210550,CVA210245,2021-02-16 13:38:21,\N
105329,1,2021-12-03 12:47:21,RPT21000061,prp,ell,HDO190987,HDO210268,2021-12-03 12:37:03,2021-12-03 12:47:21
105330,0,2021-12-03 12:47:21,RPT21000062,prp,ell,HDO190987,HDO190545,2021-12-03 12:47:21,\N

In [ ]:

saved_dfs3 = []

for j in csv_files:
    try:

        tempdf = pd.read_csv(folder_path + j)
        
        for i in tempdf.columns:
            tempdf[i] = tempdf[i].astype(str)
            if tempdf[tempdf[i].str.contains('1419/18MTALEXAND-2')].shape[0] >0:
                tempdf2 = tempdf[tempdf[i].str.contains('1419/18MTALEXAND-2')]
                tempdf2['file_name_lv'] = j
                saved_dfs3.append(tempdf2)
        print(j)

    except:
        
        print(j)
        continue

In [ ]:
tempdf4 = saved_dfs2[0]

for l in tempdf4.columns:
    tempdf4[l] = tempdf4[l].astype(str)

    if tempdf4[tempdf4[l].str.contains('HDO191147')].shape[0] >0:
        print('yes')